### ISSUE TITLE
json-coercion-matcher doesn't play well with `eq`

### ISSUE THREAD

**Issue by cemerick** [Prismatic/schema#191]
This tripped me up:

```clojure
=> ((coerce/coercer (s/eq :foo) coerce/json-coercion-matcher) "foo")
{:error (not (= :foo "foo"))}
=> ((coerce/coercer (s/enum :foo) coerce/json-coercion-matcher) "foo")
:foo
```

I didn't look into why the former doesn't yield the expected result; I'm guessing the equality constraint is "opaque" to the mapping being performed. In any case, I thought I'd leave a trail here for others.

**Comment by w01fe** [comment]
Thanks for the report.  This is because the default JSON coercions have a
case for keyword enums, but not for dispatching on `s/eq`.

https://github.com/Prismatic/schema/blob/master/src/cljx/schema/coerce.cljx#L112

If you wanted to add something that can coerce any `s/eq` based on the
class and the other coercions, a PR would be very welcome.
