### ISSUE TITLE
More useful error messages when inspecting objects

### ISSUE THREAD

**Issue by lvh** [Prismatic/schema#205]
```clojure
{:url (s/both sc/URI
                (s/pred valid-scheme? 'valid-scheme?))
   :method (s/enum :GET :POST :DELETE :PUT :PATCH :HEAD)}
```

`sc` is schema-contrib, which has a URI scheme. Otherwise irrelevant here, I think.

`valid-scheme?` is the obvious implementation:

```clojure
(defn scheme
  "Get the scheme of a URL."
  [^String url]
  (.getScheme (URI. url)))

(defn valid-scheme?
  "Checks if the given URL has a valid scheme."
  [^String url]
  (#{"http" "https"} (scheme url)))
```

When checking this schema, you get:

```clojure
{:url (not (valid-scheme? a-java.lang.String))}
```

Which isn't very useful (I know the `a-java.lang.String` is the URL object being matched against). Is there something cool I can do where schema knows about the extraction function, so that I can just do `(s/enum ["http" "https"])` and get a more useful error message, something like:

```
{:url (not (valid-scheme?
                      (not (#{:http :https} :bogus))))}
```

**Comment by lvh** [comment]
Actually, in this case, it'd be cool if I could just repeat the string being checked, I suppose.

**Comment by w01fe** [comment]
I don't think there's a built-in schema that can help you here, but I suppose you could build a 'transformed-schema' that takes a function and a schema and tries to validate the schema on the output of the function on the input.  

Schema will show the string if it's short enough, but otherwise falls back to the Class to prevent massive error messages.  We could potentially make this threshold configurable if that would be helpful.

**Comment by lvh** [comment]
Perhaps a truncation of the string would be more useful? (Also, it seems like the limit is pretty low; I'm not actually throwing big strings at it...)

**Comment by w01fe** [comment]
Well, the goal is for it to convey as much useful information as possible in a bounded amount of space.  The type is often more important than the value, so we don't always want to stringify.  That said, if you want to make it ellipsize strings rather than showing a-String a PR is welcome -- look at `utils/value-name`.   Thanks!

**Comment by w01fe** [comment]
#237 allows you to configure the length -- does this help?

**Comment by lvh** [comment]
I suppose it does; thanks!
