### ISSUE TITLE
one parameter s/one

### ISSUE THREAD

**Issue by geraldodev** [Prismatic/schema#209]
Hi,

I have this case
```
(s/def Competencia (s/both s/Str (s/pred #(re-find #"^\d{6}$" %))))
(s/def Versao (s/both s/Str (s/pred #(re-find #"^\d+$" %))))

(s/defn vec-ou-str-to-carga
  [vec-ou-str :- (s/either Competencia
                           [(s/one Competencia "c")
                            (s/one Versao "v")])]
)))
```
It would be nice if I had not to name s/one  because I've already specialized it.

I'm writing schema to my brain this week. Can't thank you enough.

Regards,

Geraldo

**Comment by w01fe** [comment]
Hi Geraldo,  

Thanks for the kind words!  When we wrote schema, we made an opinionated choice to require a name, since even when you've named the schema there's often a "role" that this schema plays in the composite type (essentially the keyword you would have used if you chose a map or record over a tuple).  Over time, we have found that occasionally this role is completely clear from context and the requirement of a name can be a bit overbearing.  That said, the name also plays an additional role -- as a way to document the position in error messages, and without making `s/one` a macro or something I don't see a great way to do that if we relax the name requirement.  

Thoughts? 

Cheers,
Jason

**Comment by geraldodev** [comment]
Jason,

I understand the pressure of making schema fast. Specially because this
crushes a lot of data on its main use.
From the point of view of the user It would be nice if it didn't forced the
named s/one.
Sorry, I can't comment on the implementation side.

Regards,
Geraldo



2015-04-27 0:21 GMT-03:00 Jason Wolfe <notifications@github.com>:
