### ISSUE TITLE
coercion error when dealing with required-key

### ISSUE THREAD

**Issue by icexelloss** [Prismatic/schema#220]
Hi,

I am trying to use coercion to make a custom transformation following https://github.com/Prismatic/schema/wiki/Writing-Custom-Transformations

I have hit an issue where required-key seems to cause my transformation to fail:

Here is my coercion function:
```
(defn simple-coercion [schema]
  (s/start-walker
   (fn [s]
     (let [walk (s/walker s)]
       (fn [x]
         (println "x:" x "s:" s )
         (let [result (if (and (or (keyword? s) (= s s/Keyword)) (string? x))
                        (walk (keyword x))
                        (walk x))]
           (println "result:" result)
           result))))
   schema))
```

I have tested this with two schema.

A:
```
(def DemoSchema
  {s/Keyword s/Str})

(let [parser (simple-coercion DemoSchema)]
    (parser {"name" "Li"}))
```
This works happily with output:
```
x: {name Li} s: {Keyword java.lang.String}
x: [name Li] s: (map-entry Keyword java.lang.String)
x: name s: Keyword
result: :name
x: Li s: java.lang.String
result: Li
result: [:name Li]
result: {:name Li}
```

And B:
```
(def DemoSchema
  {:name s/Str})

(let [parser (simple-coercion DemoSchema)]
    (parser {"name" "Li"}))
```
This gives me an error:
```
x: {name Li} s: {:name java.lang.String}
x: :schema.core/missing s: (map-entry :name java.lang.String)
result: #schema.utils.ErrorContainer{:error [:name missing-required-key]}
result: #schema.utils.ErrorContainer{:error {name disallowed-key, :name missing-required-key}}
```

I am curious why the behavior is different with these two schemas

**Comment by w01fe** [comment]
You can find some additional context on this here:

https://groups.google.com/forum/#!searchin/prismatic-plumbing/Coercing$20string$20keys$20to$20keyword$20keys%7Csort:relevance/prismatic-plumbing/HI5VGCGwzHU/UVt9aQcLK5YJ

The short answer is that for map validation to run in linear (rather than quadratic time), the key for a specific key entry is actually used to find the matching MapEntry schema.   In your latter case, we never make it to coercion time because we fail to extract a schema for the string "name".  

A couple easy (but perhaps suboptimal) solutions are to lift the coercion up a level to your map schema, or simply keywordize your maps before trying to coerce.  Will either of those work for you?

**Comment by icexelloss** [comment]
Can you elaborate a bit on "lift the coercion up a level to your map schema" ?

keywordize my maps isn't great because my actual schema is nested maps of some maps have strings as keys instead of keywords (like username)

**Comment by w01fe** [comment]
I mean take the logic that you have, but put it in a coercer on (instance?
s APersistentMap) that looks at the keys of the map schema, extracts the
keywords, and then converts the corresponding string keys in the datum to
keywords.

**Comment by icexelloss** [comment]
That makes sense. Thank you!
