### ISSUE TITLE
Compile warning with cljs 0.0-3291

### ISSUE THREAD

**Issue by tdavis** [Prismatic/schema#227]
This was mentioned in #193 but doesn't appear to have had a ticket created. With newer version of cljs, warnings like these have appeared when using ``cljsbuild auto``:

```
WARNING: map->Property at line 4 is being replaced at line 4 target/generated/cljs/schemas.cljs
WARNING: map->Source at line 9 is being replaced at line 9 target/generated/cljs/schemas.cljs
```

**Comment by w01fe** [comment]
Thanks for the ticket.  It looks like the solutions are either to (1) embed the redef in an if statement, since warnings are suppressed in that case, or (2) just don't emit this in ClojureScript at all.  The latter probably makes more sense, especially since cljs may not have the same perf issue.  We should also check if the perf issue in Clojure has been fixed, in which case it can be dropped entirely.  Here is where it is defined: https://github.com/Prismatic/schema/blob/master/src/clj/schema/macros.clj#L315  

Patches welcome!

**Comment by w01fe** [comment]
Looks like the perf of `map->Record` is fixed in Clojure 1.7, but still slow in 1.6.  Seems like best approach is to just turn it off in cljs, and eventually remove entirely.

**Comment by w01fe** [comment]
Can you please try this out and see if the warnings are fixed? 

https://clojars.org/prismatic/schema/versions/0.4.4-SNAPSHOT

I don't see them when running the tests so want to be sure.  After confirmation, I can cut a release if it would be helpful.  Thanks!

**Comment by tdavis** [comment]
Warnings are gone on this end, thanks! I can just use the snapshot for now; don't want to trouble you!
