### ISSUE TITLE
Coercions can be accidentally occluded

### ISSUE THREAD

**Issue by JakePi3** [Prismatic/schema#239]
I have a case where I want to parse a date, but under certain circumstances change it into a sentinel keyword.  Let's say that 1970-01-01 should be co-erced to :invalid

This works fine:

    (let [keyDate (s/either s/Inst (s/enum :invalid))
          dateParser (comp clj-time.coerce/to-date clj-time.coerce/from-string)
          sentinelFunc #(if (= % (dateParser "1970-01-01")) :invalid %)
          keyDateParser (comp sentinelFunc dateParser)] 
      ((schema.coerce/coercer [(s/one keyDate "u")]
                              {;s/Inst  dateParser
                               keyDate keyDateParser}) ["1970-01-02"]))

However, when I uncomment `;s/Inst dateParser` then I get an error:

`=> #schema.utils.ErrorContainer{:error [(named (not (some (check % a-java.util.Date) schemas)) "u")]}`

I would expect the keyDate coercion to take precedence, but even if it doesn't, either parser should resolve to a valid date.

**Comment by w01fe** [comment]
Coercions are applied hierarchically by design, so that, e.g. you can say once how to coerce Strings into Longs and have that work inside higher-level coercions.  

In this case the error message is a bit confusing, as is often the case for `s/either`.  What's happening is that your `sentinelFunc` is not idempotent, so the second time it's called it throws an exception because it  sees a date rather than a string.  if you make it `#(if (string? %) (clj-time.coerce/to-date (clj-time.coerce/from-string %)) %)` it should work.
