### ISSUE TITLE
(RequiredKey. :foo) doesn't validate against :foo

### ISSUE THREAD

**Issue by casperc** [Prismatic/schema#268]
Given the following schema:

    {(s/RequiredKey. :foo) s/Str :bar s/Keyword}

And then check the schema

    (s/check (make-keys-optional asdf) {:foo "asdf" :bar :foobar})
    => {:foo disallowed-key}

The expected behaviour would be to treat it the same as the schema: {:foo s/Str :bar s/Keyword}

As for why I think this is important: I want to be able to crawl and modify the schema, to make a less strict validation, where all keys that are not marked as explicitly required will be marked as optional. This gist implements it the idea (is still WIP, so doesn't cover all cases): https://gist.github.com/casperc/250fa30d7ac96965d177#file-schema-optional-keys-cljs

This would give the following behaviour for that schema:
  - fail if given a key not in the schema (as normal)
  - fail if given a wrong type (as normal)
  - pass if the validator is given a map with only the subset of defined keys in the schema.

Currently, I can't mark keys as explicitly required (required-key returns the key if given a keyword). I would be fine with doing this with `(RequiredKey. :foo)` instead of the helper function required-key to avoid breaking existing behaviour (if the validation gets updated to work as expected).

**Comment by w01fe** [comment]
I think the specific issue is that you're double-wrapping required keys in optional keys.  

The correct way to `make-key-optional` would be `(if (s/specific-key? k) (s/optional-key (s/explicit-schema-key k)) k)`.  

You'll also have to tread lightly when walking like this.  Checking for the concrete map classes would help you avoid the records rather than doing it case-by-case, but there may be other weird cases.  

FWIW you can do this with coercion without changing the schemas.  

https://groups.google.com/forum/#!topic/prismatic-plumbing/lLCEcSh4cpw

HTH, Jason

**Comment by w01fe** [comment]
As for the specific issue in the title, that also works fine for me:

`(s/validate {(s/->RequiredKey :foo) s/Str} {:foo "a"})`

can you provide a minimal failing case?

**Comment by w01fe** [comment]
As for the specific issue in the title, that also works fine for me:

`(s/validate {(s/->RequiredKey :foo) s/Str} {:foo "a"})`

can you provide a minimal failing case?   Also be aware that the RequiredKey record itself is considered an implementation detail and subject to change, although we're unlikely to do so anytime soon.

**Comment by casperc** [comment]
You are entirely right, it does work. I am sorry, I must have confused myself somehow. I'll close the issue, it totally works as expected.

Thanks for the pointer for doing it with coercion, that seems like a better way of doing it.

**Comment by w01fe** [comment]
No worries.  Keep in mind that the coercion solution would actually remove the extra keys from the map, which might not be quite what you want now that I think about it further.  

My suggestion if you're just trying to avoid typing `optional-key` a lot would be to define a `default-optional` function that takes a map schema and makes all the keys optional, and call that explicitly when you want to create a schema like this (rather than trying to walk a whole graph of schemas after the fact).
