### ISSUE TITLE
'Writing Custom Transformations' references removed variables

### ISSUE THREAD

**Issue by MichaelBlume** [Prismatic/schema#278]
walker and start-walker are no longer present, so the patterns described in 'Writing Custom Transformations' no longer work. Is there a page describing migration from 0.x to 1.x?

**Comment by w01fe** [comment]
Given that the core protocol is now declarative, it depends to some degree on whether your use case fits into the `checker` framework or not.  

Coercers do, so they look much like before:

https://github.com/Prismatic/schema/blob/master/src/cljx/schema/coerce.cljx#L26

Generators don't (they don't return datums, but generators), so they instead define a new protocol and extend it to the schema types: 

https://github.com/Prismatic/schema/blob/master/src/clj/schema/experimental/generators.clj#L36

If you can provide more details on your use case, I can provide guidance on how to best implement in 1.0.  Help updating the docs would be welcome, otherwise we'll get to it when we can.  Thanks!

**Comment by gavilancomun** [comment]
Here's my use case. I have been using a modified version of the (start-walker) example in the wiki to produce a filtered trace in the case of failed schema parses.

https://gist.github.com/gavilancomun/7bd89368e1f42a6c1737

There is no coercion as such, it's the side effect of producing the trace messages I am interested in. They help me to debug a fairly deeply nested schema.

**Comment by w01fe** [comment]
Thanks for that info.  I think this diff for coercers should basically show the changes you need:

https://github.com/Prismatic/schema/commit/0072a7461b9f408708bd7b30f63170c621f57861?w=1#diff-bc4ae2a20f04bd9cf6c4e0fe8fde845dR29

 - `start-walker` became `run-checker`. 
 - the function it takes does not need to be memoized for performance
 - the function it takes wants an additional params
 - you now call `(spec/checker (s/spec s) params)` rather than `(s/walker s)` inside that function.
 - you pass a new second argument of true or false, indicating whether you want 'coerced' values out or are only interested in errors.

LMK if you have any questions.

**Comment by w01fe** [comment]
Just updated the wiki page: 

https://github.com/Prismatic/schema/wiki/Writing-Custom-Transformations

Please reopen if there are further questions / issues with the updated page.  Thanks!
