### ISSUE TITLE
How to match keys using regex

### ISSUE THREAD

**Issue by punit-naik** [Prismatic/schema#317]
I have a map which has several keys like :machines, :es_machines, :hadoop_machines. In my schema I want to match all these keys with a regex so that I don't have to list down these keys. How do I do this?

**Comment by w01fe** [comment]
First, can you please post questions on the mailing list (see the README) -- we prefer to keep Github Issues for bug reports and such.  

As for your question, if you have only one such wildcard, you could do something like 
`{(s/constrained Keyword #(re-matches #"..." (name %))) ValueSchema}`.  

Note that only one non-explicit key schema is allowed, so that matching can be done in linear time.  So it's not currently possible to have two such wildcards in a single map schema.  In that case, you could always write your own map schema type, use predicate validation, or write code to produce an explicit map schema with all the keys.

**Comment by punit-naik** [comment]
Thanks a lot @w01fe :+1:  I will post questions on mailing list from next time :+1:

**Comment by w01fe** [comment]
No problem, thanks -- happy to answer follow-up questions on the mailing list :)
