### ISSUE TITLE
Why isn't maybe visible in s/spec?

### ISSUE THREAD

**Issue by mattiasw2** [Prismatic/schema#327]
I manipulate my schemas a lot, i.e. build new ones, combine them, create subtypes. Should I write this code using s/explain or s/spec output? What is recommended? 

Is the definition of s/maybe that there is no wrapping {:schema ??} ?

````
(ns sss4.Xmldb.BO.schematest1
  (:require
   [schema.core :as s]
   [clojure.pprint :as pp]
   ))

(s/defrecord Test1
    [id :- s/Str
     username :- (s/maybe s/Str)])

(pp/pprint (s/explain Test1))

=> (record
 sss4.Xmldb.BO.schematest1.Test1
 {:id Str, :username (maybe Str)})

(pp/pprint (s/spec Test1))

=> {:pre #function[schema.spec.core/precondition$fn--333],
 :options
 [{:schema
   {:klass sss4.Xmldb.BO.schematest1.Test1,
    :schema
    {:id java.lang.String, :username {:schema java.lang.String}}}}],
 :err-f nil,
 :post nil}
````

**Comment by w01fe** [comment]
Thanks for your question.  We'd like to keep Github Issues for bug reports and feature requests; in the future, can you please post questions on the mailing list?  Thanks! 

As for the question, it's not clear to me what exactly you're trying to accomplish.  The reason you see `{:schema java.lang.String}` here is because that's how `pprint` prints records (such as schema.core.Maybe) by default -- if you examine the spec, you will find the `s/maybe` schema in there as expected.  If you can provide some more details of what you are trying to do, then we can try to help provide more guidance.

**Comment by mattiasw2** [comment]
Ok, I misunderstood the purpose of the spec function. I thought it returned a datastructure that I could use to process schemas.
